In [1]:
import pandas as pd
df = pd.read_csv('results.csv')

In [2]:
comparison = df.iloc[:, [1,2]].values

In [3]:
import numpy as np
samples = comparison.shape[0]
conf_matrix = np.zeros( (5, 5) , dtype=np.int32 )

for i in range(samples):
    conf_matrix[ int(comparison[i][0]) ][ int(comparison[i][1])  ] += 1

print(conf_matrix)

[[1901    2   28    7   45]
 [  13  494  755   11  186]
 [ 137   38 3492    7  473]
 [ 155   23   53  806   55]
 [  10    5   27    0 2413]]


In [6]:
safe_for_work_label = 3
tp = 0
for i in range(5):
    for j in range(5):
        if i != safe_for_work_label or j != safe_for_work_label:
            tp += conf_matrix[i][j]


tn = conf_matrix[3][3]

fp = conf_matrix[3][0] + conf_matrix[3][1]  + conf_matrix[3][2] + conf_matrix[3][4]  
fn = conf_matrix[2][3] + conf_matrix[1][3]  + conf_matrix[0][3] + conf_matrix[4][3] 

recall = tp / (tp + fn)
precision = tp / (tp + fp)
accuracy = (tp + tn) / (tp + fp + tn + fn)

print(accuracy , precision , recall)


0.9728313095134097 0.9730595327807083 0.9975857073877354
